/**
 * WorkManagementSystemTAB
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AccessLevelEnum = 0 | 1 | 2 | -1;

export const AccessLevelEnum = {
  Worker: 0 as AccessLevelEnum,
  Manager: 1 as AccessLevelEnum,
  Admin: 2 as AccessLevelEnum,
  Undefined: -1 as AccessLevelEnum,
};
